# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Flat
version:      0.91
version_from: lib/File/Flat.pm
installdirs:  site
requires:
    Class::Autouse:                1
    Class::Inspector:              0
    File::Copy:                    0
    File::Find:                    0
    File::NCopy:                   0.32
    File::Remove:                  0.2
    File::Spec:                    0.82
    File::Temp:                    0.12
    IO::File:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
