name: File-Flat
version: 0.93
abstract: Filesystem interface where directories are abstracted away
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  Test::ClassAPI: 1.02
  File::Find: 0
requires:
  perl: 5.005
  File::Spec: 0.85
  File::Copy: 0
  File::NCopy: 0.32
  File::Slurp: 9999.04
  File::Remove: 0.21
  File::Temp: 0.14
  IO::File: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
